# This is a basic workflow to help you get started with Actions

name: Build Pack(s)

# Controls when the workflow will run - only when modifying pack
on:
  push:
    paths:
      - 'main/**'
      - 'sharders/**'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# Download stuff
  setup:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup RCON connection
        run: |
          sudo apt-get install build-essential
          git clone https://github.com/Tiiffi/mcrcon.git
          cd mcrcon
          make
          sudo make install

      - name: Setup MinIO
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin/

      - name: Set Up MinIO Configuration
        run: |
          mc alias set myminio https://mcapi.nikodaproot.pl/ "${{ secrets.MINIO_ACCESS_KEY }}" "${{ secrets.MINIO_SECRET_KEY }}"
          
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            .github/cache # Try to improve build times because why not 
          key: ${{ runner.os }}-dependencies-${{ hashFiles('.github/cache') }}








  # Build the root pack
  build_main:
    needs: setup
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v3
      


      - name: Prepare File
        run: |
         cd main
         zip -r ../nikosnextbots_pack.zip *


      - name: Upload to Host
        run: |
         mc cp nikosnextbots_pack.zip myminio/nnb/





  # Build the sharders pack
  build_sharders:
    needs: setup
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v3
      

      - name: Prepare File
        run: |
         cd sharders
         zip -r ../nikosnextbots_sharders.zip *


      - name: Upload to Host
        run: |
         mc cp nikosnextbots_sharders.zip myminio/nnb/





# Push update
  push_update:
    needs: 
      - build_main
      - build_sharders
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Reload the server script - push
      - name: Import Texturepack
        run: mcrcon -H ${{ secrets.RCON_IP }} -P ${{ secrets.RCON_PORT }} -p ${{ secrets.RCON_PASSWORD }} "forcepack reload"
