# This is a basic workflow to help you get started with Actions

name: Build Datapacks

# Controls when the workflow will run - only when modifying pack or pushing changes etc
on:
  push:
    branches:
      - txt-main
    paths:
      - 'nnb_possessions/**'
      - 'nnb_vote_system/**'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:



# -----------------------------------------
# Build datapacks
# -----------------------------------------





  # Build the root pack
  build_possessions_sys:
    runs-on: ubuntu-latest
  #  needs: [validate_main]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


  
      - name: Prepare File
        run: |
         cd nnb_possessions
         zip -r ../nnb_possessions.zip *


      - name: Upload to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 2022
          source: nnb_possessions.zip
          target: /world/datapacks


  # Build the voting system
  build_voting_sys:
    runs-on: ubuntu-latest
  #  needs: [validate_main]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


  
      - name: Prepare File
        run: |
         cd nnb_vote_system
         zip -r ../nnb_vote_system.zip *


      - name: Upload to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 2022
          source: nnb_vote_system.zip
          target: /world/datapacks














  push_texturepack:
    runs-on: ubuntu-latest
    needs: [build_possessions_sys, build_voting_sys]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      - name: Setup RCON connection
        run: |
          sudo apt-get install build-essential
          git clone https://github.com/Tiiffi/mcrcon.git
          cd mcrcon
          make
          sudo make install

      - name: Import Texturepack
        run: mcrcon -H ${{ secrets.ARCADE_RCON_IP }} -P ${{ secrets.ARCADE_RCON_PORT }} -p ${{ secrets.ARCADE_RCON_PASSWORD }} "minecraft:reload"
