# This is a basic workflow to help you get started with Actions

name: Build Datapacks

# Controls when the workflow will run - only when modifying pack or pushing changes etc
on:
  push:
    branches:
      - txt-main
    paths:
      - 'nnb_possessions/**'
      - 'nnb_vote_system/**'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:



# -----------------------------------------
# Build datapacks
# -----------------------------------------





  # Build the root pack
  build_possessions_sys:
    runs-on: ubuntu-latest
  #  needs: [validate_main]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


  
      - name: Prepare File
        run: |
         cd nnb_possessions
         zip -r ../nnb_possessions.zip *


      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.SFTP_USERNAME }}
            server: ${{ secrets.SFTP_SERVER }}
            port: 2022
            local_path: './nnb_possessions.zip'
            remote_path: '/world/datapacks/'
            sftp_only: true
            password: ${{ secrets.SFTP_PASSWORD }}





  build_vote_sys:
    runs-on: ubuntu-latest
  #  needs: [validate_main]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


  
      - name: Prepare File
        run: |
         cd nnb_possessions
         zip -r ../nnb_vote_system.zip *


      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.SFTP_USERNAME }}
            server: ${{ secrets.SFTP_SERVER }}
            port: 2022
            local_path: './nnb_vote_system.zip'
            remote_path: '/world/datapacks/'
            sftp_only: true
            password: ${{ secrets.SFTP_PASSWORD }}















  push_datapack:
    runs-on: ubuntu-latest
    needs: [build_possessions_sys, build_vote_sys]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      - name: Setup RCON connection
        run: |
          sudo apt-get install build-essential
          git clone https://github.com/Tiiffi/mcrcon.git
          cd mcrcon
          make
          sudo make install

      - name: Import Texturepack
        run: mcrcon -H ${{ secrets.ARCADE_RCON_IP }} -P ${{ secrets.ARCADE_RCON_PORT }} -p ${{ secrets.ARCADE_RCON_PASSWORD }} "minecraft:reload"
