# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      

            

      

      # Runs a single command using the runners shell
      - name: Zip the file
        run: zip -r publish/test.zip VibeCraft_nextbots
        
   #   - name: Prepare to upload
    #    uses: deka0106/upload-to-dropbox@v2.0.0

      - name: Dropbox Uploader
  # You may pin to the exact commit or the version.
  # uses: whalemare/action-dropbox@cdf61122bd57666ca3ec5f61b82b7b8d28315b18
        uses: whalemare/action-dropbox@v1.0.0
        with:
    # Dropbox access token. Create new one at: https://www.dropbox.com/developers/apps
         accessToken: ${{secrets.DROPBOX_ACCESS_TOKEN}}
    # glob pattern for file (ex. src/**/*)
         pattern: publish/* # optional, default is default value if applicable
    # path to specific file (ex. src/main.ts)
         file: publish/* # optional
    # Dropbox destination path for uploading. Must be started from /". (ex. "/actions", "/actions/main.ts")
         destination: / # optional
          
