name: Generate Dropbox Access Token

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  generate-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change this to your desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dropbox

      - name: Generate Access Token
        run: |
          python - <<EOF
          import dropbox

          app_key = '${{ secrets.DROPBOX_APP_KEY }}'
          app_secret = '${{ secrets.DROPBOX_APP_SECRET }}'

          auth_flow = dropbox.DropboxOAuth2FlowNoRedirect(app_key, app_secret)
          authorize_url = auth_flow.start()

          print(f'Authorize your app by visiting: {authorize_url}')

          auth_code = input('Enter the authorization code: ')

          access_token, user_id = auth_flow.finish(auth_code)

          print(f'::set-output name=DROPBOX_ACCESS_TOKEN::{access_token}')
          EOF
        env:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
