

name: Check JSON Files

on:
  push:
    branches: [ "txt-testing" ]
  pull_request:
    branches: [ "txt-testing" ]
  repository_dispatch:
    types:
      - run

  workflow_dispatch:

jobs:
  validate_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON Files - Main
        run: |
          cd main
          for file in $(find . -type f -name "*.json"); do
            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
          done




  validate_sharders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Check sharders folder  
      - name: Validate JSON Files - Sharders
        run: |
          cd sharders
          for file in $(find . -type f -name "*.json"); do
            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
          done



  validate_custom:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/txt-testing'
    steps:
      - uses: actions/checkout@v3
        # Check sharders folder  
      - name: Validate JSON Files - Custom
        run: |
          cd custom
          for file in $(find . -type f -name "*.json"); do
            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
          done
