

name: Check JSON Files

on:
  push:
    branches: [ "txt-main" ]
  pull_request:
    branches: [ "txt-main" ]

  workflow_dispatch:

jobs:
  validate_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      # Check main folder
      - name: Validate JSON Files - Main
        run: |
          cd main
          for file in $(find . -type f -name "*.json"); do
            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
          done

        # Check sharders folder  
      - name: Validate JSON Files - Main
        run: |
          cd sharders
          for file in $(find . -type f -name "*.json"); do
            jq empty "$file" >/dev/null || (echo "Error in JSON file: $file" && exit 1)
          done
